Fix github action deploy.yml
Implement dynamic tagging - attempt #2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,12 +36,6 @@ jobs:
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
 
-      - name: Debug env variable
-        run: |
-          echo "ECR_REGISTRY: $ECR_REGISTRY"
-          echo "ECR_REPOSITORY: $ECR_REPOSITORY"
-          echo "IMAGE_TAG: $IMAGE_TAG"  
-
       - name: Build, tag,& push docker image
         env: 
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
@@ -57,8 +51,17 @@ jobs:
           echo "Tag the build image"
           docker tag mymonorepo-ecr-trial-0 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
+          echo "Verifying tagged build image..."
+          docker images | grep $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || echo "tagged image not found!"
+
           echo "Pushing image to ECR..."
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+
+      - name: Debug env variable
+        run: |
+          echo "ECR_REGISTRY: $ECR_REGISTRY"
+          echo "ECR_REPOSITORY: $ECR_REPOSITORY"
+          echo "IMAGE_TAG: $IMAGE_TAG"  
 
       - name: Deploy to Amazon Copilot 
         run: |
