Fix github action deploy.yml
implement dynamic tagging - attempt #1

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -48,14 +48,14 @@ jobs:
           ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
           IMAGE_TAG: ${{ github.sha }} # use a unique tag
         run: |
-          echo "Building image: mymonorepo_ecr_trial_3 "
-          docker build -f dockerfile_nginx -t mymonorepo_ecr_trial_0 .
+          echo "Building image: mymonorepo-ecr-trial-0 "
+          docker build -f dockerfile_nginx -t mymonorepo-ecr-trial-0 .
 
           echo "Verifying build image..."
-          docker images | grep mymonorepo_ecr_trial_0 | echo "image not found!"
+          docker images | grep mymonorepo-ecr-trial-0 || echo "image not found!"
 
           echo "Tag the build image"
-          docker tag mymonorepo_ecr_trial_3:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+          docker tag mymonorepo-ecr-trial-0 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
           echo "Pushing image to ECR..."
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
