Trigger CD Test #5

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -42,14 +42,15 @@ jobs:
           ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
           IMAGE_TAG: 'latest' 
         run: |
-          echo "Building image: mymonorepo-ecr-trial-0 "
-          docker build -f dockerfile_nginx -t mymonorepo-ecr-trial-0 .
+          LOCAL_IMAGE_TAG=$(git rev-parse --short HEAD) 
+          echo "Building image: mymonorepo-ecr-trial-0:$LOCAL_IMAGE_TAG "
+          docker build -f dockerfile_nginx -t mymonorepo-ecr-trial-0:$LOCAL_IMAGE_TAG .
 
           echo "Verifying build image..."
-          docker images | grep mymonorepo-ecr-trial-0 || echo "image not found!"
+          docker images | grep mymonorepo-ecr-trial-0:$LOCAL_IMAGE_TAG || echo "image not found!"
 
           echo "Tag the build image"
-          docker tag mymonorepo-ecr-trial-0 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+          docker tag mymonorepo-ecr-trial-0:$LOCAL_IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
           echo "Verifying tagged build image..."
           docker images | grep $IMAGE_TAG || echo "tagged image not found!"
