Trigger CD Test #7

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -49,23 +49,22 @@ jobs:
           docker images | grep $LOCAL_IMAGE_TAG || echo "image not found!"
 
           echo "Tag the build image"
-          docker tag mymonorepo-ecr-trial-0:$LOCAL_IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:tagged-$LOCAL_IMAGE_TAG
+          docker tag mymonorepo-ecr-trial-0:$LOCAL_IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
 
           echo "Verifying tagged build image..."
-          docker images | grep tagged-$IMAGE_TAG || echo "tagged image not found!"
+          docker images | grep $ECR_REGISTRY/$ECR_REPOSITORY:latest || echo "tagged image not found!"
 
-          echo "Pushing image to ECR... $ECR_REGISTRY/$ECR_REPOSITORY:tagged-$IMAGE_TAG"
-          docker push $ECR_REGISTRY/$ECR_REPOSITORY:tagged-$IMAGE_TAG 
+          echo "Pushing image to ECR... $ECR_REGISTRY/$ECR_REPOSITORY:latest"
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest 
 
       - name: Deploy to Amazon Copilot 
         run: |
-          LOCAL_IMAGE_TAG=$(git rev-parse --short HEAD) 
           curl -Lo copilot-cli https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
           chmod +x copilot-cli
           sudo mv copilot-cli /usr/local/bin/copilot
           echo "Deploying to the following environment: $DEPLOY_ENV"
           copilot svc deploy --name ${{ secrets.ECS_SERVICE }} --env $DEPLOY_ENV \
-          --force -- image $ECR_REGISTRY/$ECR_REPOSITORY:tagged-$IMAGE_TAG #pass explicit image     
+          --force -- image $ECR_REGISTRY/$ECR_REPOSITORY:latest #pass explicit image     
 
 
 
